@startuml

package toys{

    +abstract class Toy #white{
    }

    +abstract class ToyBall{
    }

    +class ToyBallsForBoys {
    }
    +class ToyBallsForGirls {
    }
    
    +abstract class ToyDoll{
    }
    
    +class ToyDollsForBoys {
    }
    +class ToyDollsForGirls  {
    }
    
    
    ToyDoll -down-|> Toy #black

    ToyBallsForGirls -left-|> ToyBall
    ToyBallsForBoys -right-|> ToyBall
    
    ToyBall -up-|> Toy #black
    
    ToyDollsForBoys -right-|> ToyDoll
    ToyDollsForGirls -left-|> ToyDoll
    
}

+class ToyProducer #lightgrey{
}

+interface Factory{
}


+enum ToyType #white{
}

+class ToyBoyFactory {
}

+class ToyGirlFactory {
}


ToyProducer -down-> Factory
ToyProducer -left-> ToyType


ToyBoyFactory .right.|> Factory
ToyGirlFactory .left.|> Factory

'ToyType .down.|> Factory #black
ToyType <-up-> Factory #black

ToyType .down.> ToyBoyFactory #black
ToyType .down.> ToyGirlFactory #black


ToyGirlFactory .down..> ToyDollsForGirls
ToyGirlFactory .down..> ToyBallsForGirls

ToyBoyFactory .down..> ToyDollsForBoys
ToyBoyFactory .down..> ToyBallsForBoys


@enduml