@startuml

package singleton {

    +class Single{
            +{field} {static} single Single
        --
            - {method} Single ()
        ..
            + {method} {static} instanceOf () : Single
    }

    Single --o Single




}

@enduml