@startuml

+class ToyProducer{
        +{field} Factory
    --
        +{method} Toy produceToy (String)
}

+abstract class Toy{
        +{field} String toyName
        +{field} boolean forGirls
    --
}

+class ToyBall extends Toy{
}

+class ToyDoll extends Toy{
}

+class Factory{
    --
        +{method} Toy constructToy(String)
}

ToyProducer -right-* Toy

ToyProducer -up-o Factory
Factory .up.> ToyBall
Factory .up.> ToyDoll

@enduml