@startuml

+class ToyProducer{
        +{field} Factory
    --
        +{method} Toy produceToy (String){constructToy(...)}
}

+class Toy{
        +{field} String toyName
        +{field} boolean forGirls
    --
}

-class ToyBall extends Toy{
}

-class ToyDoll extends Toy{
}

+interface Factory{
    --
        +{method} Toy constructToy(String)
}

+enum ToyType{
BALL {constructToy(...)},
DOLL {constructToy(...)},
}

ToyProducer -right-* Toy

ToyProducer -up-o ToyType
ToyType -right-|> Factory
ToyType .up.> ToyBall
ToyType .up.> ToyDoll

@enduml