@startuml

+class ToyProducer{
    --
        +{method} Toy produceToy(String)
}

+abstract class Toy{
        +{field} String toyName
        +{field} boolean forGirls
    --
}

+class ToyBall extends Toy{
}

+class ToyDoll extends Toy{
}

ToyProducer .left.> Toy

@enduml