@startuml

+class ToyProducer{
    --
        +{method} Toy produceToy(String)
}

+class Toy{
        +{field} String toyName
        +{field} boolean forGirls
    --
}

+class ToyBall extends Toy{
}

+class ToyDoll extends Toy{
}

ToyProducer ..> Toy

@enduml