@startuml

hide Client field

class Client{
    ~{method}{static} callOperation (context : String)
}

Client ..> Abstraction : callOperation

Abstraction *-right-> "2" Implementation #blue

class Abstraction {
        ~{field} implementation : HashMap (context : String, impl : Implementation)
    --
        ~{method} callOperation (name: String)
}

note bottom of Abstraction #white : callOperation { ...implementedOperation }

hide Implementation field
abstract class  Implementation  {
    ~{method}{abstract} implementedOperation
}

hide  ImplementationA member
class ImplementationA extends Implementation{
}

hide  ImplementationB member

class ImplementationB extends Implementation{
}

@enduml