@startuml

+abstract class Node{
        +{field}{static} final Node nullNode
    ..
        +{field} Node prev = nullNode;
        +{field} Node next = nullNode;
        +{field} double value
        +{field} String operationType = ""
    --
        +{method} join (Node)
        +{method} leave ()
        +{method} boolean isEmpty
        +{method} operate
    ..getters & setters..
}

+class RealNode extends Node{
}

+class NullNode extends Node{
        +{field} String operationType = "null"
    --
        +{method} join (Node)
        +{method} leave ()
        +{method} boolean isEmpty
        +{method} operate
    ..getters & setters..

}

@enduml