@startuml

+abstract class Node{
        +{field}{static} Node : nullNode {final}
    ..
        +{field} prev : Node = nullNode;
        +{field} next : Node = nullNode;
        +{field} value : double
        +{field} operationType : String = ""
    --
        +{method} join : Node
        +{method} leave
'        +{method} isEmpty : boolean
        +{method} operate
'    ..getters & setters..
}

+class RealNode extends Node{
}
    hide RealNode member

+class NullNode extends Node{
    -- @Overrides--
        +{method} join : Node
        +{method} leave
        +{method} operate
    ..getters & setters..
'        +{method} isEmpty : boolean = true
        +{method} getValue : double = NaN
        +{method} getPrev : Node = self
        +{method} getNext : Node = self
        +{method} getOperationType : String = "null"
}

@enduml